### ISSUE TITLE
this.$form on Laravel components

### ISSUE THREAD

**Issue by marianvlad** [MetinSeylan/Vue-Laravel-Validator#1]
Hi, there is a way to use this.$form inside components on Laravel 5.3?

**Comment by marianvlad** [comment]
I think it's a problem on vue 2.0.1

```
this.$form is not a function
```

**Comment by MetinSeylan** [comment]
``` js
import Vue from 'vue';
import VueResource from 'vue-resource';
import LaravelValidator from 'vue-laravel-validator';

Vue.use(VueResource);
Vue.use(LaravelValidator); // => this method required
```

**Comment by marianvlad** [comment]
The problem is with vuejs. They changed init method from mixin with beforeCreate.

**Comment by marianvlad** [comment]
The problem is with vuejs, they replaced init method with beforeCreate in mixin a16a13c6c5742229f6639d472607d019a8cd8fdb

**Comment by anindya-dhruba** [comment]
@MetinSeylan can you make an update that @marianvlad suggested?

**Comment by MetinSeylan** [comment]
thanks for feedback #fixed
