### ISSUE TITLE
Example with Vuex.

### ISSUE THREAD

**Issue by san4io** [MetinSeylan/Vue-Laravel-Validator#4]
Hello, once again

I would like to see more complex example with Vue2.0 and Vuex 2.0,

I can't manage to pass values from vuex to form.

Lets assume i have store with user.

```
this.$store.state.user = {
    email: 'email',
    name: 'name'
}
```

How should i get user state to form

```
data() {
    return {
        form: this.$form({
            email: '', // What should be written here?
            name: ''
        })
    }
}
```

**Comment by MetinSeylan** [comment]
``` js
data() {
    return {
        form: this.$form({
            email:  this.$store.state.user.email ,
            name: this.$store.state.user.name
        })
    }
}
```

but, i am not sure :)

**Comment by san4io** [comment]
Ha,ha.

I tried to. :DDD
But it doesn't work for me. :) If I'll find solution i'll let you know. :)

**Comment by MetinSeylan** [comment]
okay, i trying on fresh project
